### model
model_name_or_path: ../../../models/bert-base-multilingual-cased
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: OBQA
template: bert_qa
cutoff_len: 512
max_samples: 5000
overwrite_cache: true
preprocessing_num_workers: 16
dataset_dir: ../../../data

### output
output_dir: ../../../saves/common_sense_reasoning/OBQA/bert-base-multilingual-cased_lora-rank_8_finetune
logging_steps: 10
save_steps: 1
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 0.5
lr_scheduler_type: cosine
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: ../../../saves/common_sense_reasoning/OBQA/bert-base-multilingual-cased_lora-rank_8_pretrain/checkpoint-140
### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
