### model
model_name_or_path: ../../../models/Mistral-7B-Instruct-v0.3
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: ARC-e
template: mistral
cutoff_len: 32768 # max_position_embeddings in config.json
max_samples: 5000
overwrite_cache: true
preprocessing_num_workers: 16
dataset_dir: ../../../data

### output
output_dir: ../../../saves/common_sense_reasoning/ARC-e/Mistral-7B-Instruct-v0.3_lora-rank_8_pretrain
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 4.5
lr_scheduler_type: cosine
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: False
### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
