### model
model_name_or_path: ../../../models/llama-7b
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: PIQA
template: llama2
cutoff_len: 2048 # max_position_embeddings in config.json
### max_samples: 5000
overwrite_cache: true
preprocessing_num_workers: 16
dataset_dir: ../../../data

### output
output_dir: ../../../saves/common_sense_reasoning/PIQA/llama-7b_lora-rank_8_finetune
logging_steps: 10
save_steps: 1
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-5
num_train_epochs: 0.27
lr_scheduler_type: cosine
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: ../../../saves/common_sense_reasoning/PIQA/llama-7b_lora-rank_8_pretrain/checkpoint-2015
### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
